feat: User, Film, Controllers classes and Tests
Brill1983/java-filmorate pull request #2
Opened 2023-06-05 09:48 UTC by Brill1983

2023-06-05 20:11 UTC, Frilock requested changes
Добрый вечер, оставил ряд комментариев к работе, жду новую версию.

2023-06-05 20:11 UTC, Frilock commented on pom.xml
> +			<version>1.18.20</version>
Версии библиотек, которые вы подключаете в pom файле, принято указывать в properties, по аналогии с версией Java, а в поле version самой библиотеки указывать так ${example-lib.version}. Это нужно для того, чтобы версии библиотек находились в одном месте и их изменении проходило безболезненно.

2023-06-05 20:11 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getName().isBlank() || film.getName() == null) {
Валидацию из ваших методов add и update нужно вынести в отдельный приватный метод, поскольку она почти полностью совпадает

2023-06-05 20:11 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film addFilm(@RequestBody Film film) {
Во первых, в данном случае у вас ошибка, поскольку условия проверяются слева на право, поэтому тут возможно NPE. Кроме того, советую вам воспользоваться библиотекой от apache common 3 и использовать тут метод StringUtils.isBlank, который объединяет данные проверки (там еще довольно много полезных методов)

2023-06-05 20:11 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ValidationException.java
> +    public ValidationException(String s) {
я бы предложил поле все таки назвать message =)

2023-06-05 20:11 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NonNull private int id = 0;
Каждая аннотация пишется на новой строке.

2023-06-05 20:11 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    FilmController filmController;
К полям необходимо добавить приватные модификаторы, правила оформления кода в тестах такое же как и в обычном бизнес коде

2023-06-05 20:11 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getReleaseDate().isBefore(LocalDate.of(1895, 12, 28))) {
Дата LocalDate.of(1895, 12, 28) является каким то магическим числом, обычно принято такие "магические" данные выносить в константные поля класса (private static final String EXAMPLE_NAME = ....)

2023-06-05 20:11 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> getFilmList() {
Логичнее назвать метод getAllFilms, или просто getAll

2023-06-05 20:11 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    int id = 0;
Отсутствует модификатор

2023-06-05 20:11 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getEmail().isBlank() || user.getLogin().isBlank()) {
Валидационный код нужно вынести в отдельный приватный метод

2023-06-05 20:11 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getName() == null || user.getName().isBlank()) {
Предлагаю использовать StringUtils

2023-06-05 20:11 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @RequestMapping(value = "/users", method = RequestMethod.POST)
value = "/users" повторяется над каждым методом данного класса, чтобы общий префикс не писать везде, то можно над классом повесить аннотацию - RequestMapping(value = ...)

2023-06-05 20:11 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NonNull private int id = 0;
Вообще в данной работе вам предлагали использовать валидацию от хибернейта или написать самому, по сути у вас дублируется валидация. Но не особо возражаю - попробовали и то и другое

2023-06-05 20:11 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +    UserController userController;
Аналогично

2023-06-06 07:48 UTC, Brill1983 commented on pom.xml
> +			<version>1.18.20</version>
Поправил.

2023-06-06 07:50 UTC, Brill1983 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film addFilm(@RequestBody Film film) {
Спасибо, очень удобный инструмент StringUtils. Взял на изучение, буду пользоваться. Тут поправил.

2023-06-06 07:51 UTC, Brill1983 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getName().isBlank() || film.getName() == null) {
Перенес в новый класс FilmValidator, со статическим методом valid.

2023-06-06 07:52 UTC, Brill1983 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getReleaseDate().isBefore(LocalDate.of(1895, 12, 28))) {
Поправил.

2023-06-06 07:52 UTC, Brill1983 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> getFilmList() {
Поправил

2023-06-06 07:53 UTC, Brill1983 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    int id = 0;
Поправил

2023-06-06 07:54 UTC, Brill1983 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @RequestMapping(value = "/users", method = RequestMethod.POST)
Поправил.

2023-06-06 07:55 UTC, Brill1983 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getEmail().isBlank() || user.getLogin().isBlank()) {
Вынес в отдельный класс UserValidator со статическим методом valid.

2023-06-06 07:55 UTC, Brill1983 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getName() == null || user.getName().isBlank()) {
Поправил

2023-06-06 07:56 UTC, Brill1983 commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ValidationException.java
> +    public ValidationException(String s) {
переименовал

2023-06-06 07:56 UTC, Brill1983 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NonNull private int id = 0;
поправил

2023-06-06 07:59 UTC, Brill1983 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    FilmController filmController;
Поправил

2023-06-06 07:59 UTC, Brill1983 commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +    UserController userController;
Поправил

2023-06-06 16:46 UTC, Frilock approved these changes
Принято

2023-06-06 16:55 UTC, merged