Add database
Brill1983/java-filmorate pull request #4
Opened 2023-07-16 18:18 UTC by Brill1983

2023-07-16 20:36 UTC, Frilock requested changes
Добрый вечер, оставил ряд комментариев в коде.

2023-07-16 20:36 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        return new ErrorResponse(errors.toString()); // для вывода трейса или
Закомментированного кода в приложении быть не должно

2023-07-16 20:36 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +    Genre findGenreById(@PathVariable int id) {
Отсутствует модификатор доступа

2023-07-16 20:36 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +@Slf4j
Лишняя аннотация

2023-07-16 20:36 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaCategoryController.java
> +    MpaCategory findMpaCategoryById(@PathVariable int id) {
Отсутствует модификатор

2023-07-16 20:36 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaCategoryController.java
> +@Slf4j
Лишняя аннотация

2023-07-16 20:36 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    public boolean equals(Object o) {
Вроде стандартный equals и hashCode, почему бы не воспользоваться аннотацией от ломбок? Кроме того, тогда ряд аннотаций можно убрать и использовать Data

2023-07-16 20:36 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Film film2 = filmStorage.addFilm(film);
Использование префиксов и окончаний числовых не приветствуется, лучше переменную переименовать =)

2023-07-16 20:36 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        filmValidator.valid(film);
А нельзя внутри valid проверять так же идентификатор? Выглядит как то странно

2023-07-16 20:36 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +    public Genre findGenreById(int id) { // TODO check how works validation
Что за TODO в коде?) Либо уберите, либо добавьте что хотели

2023-07-16 20:36 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +@Slf4j
Лишняя аннотация

2023-07-16 20:36 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaCategoryService.java
> +@Slf4j
Лишняя аннотация

2023-07-16 20:36 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        System.out.println(rate);
println в коде не используют, либо логгируйте, либо просто уберите

2023-07-16 20:36 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        int rate = rs.getInt("RT");
Лишняя строчка вроде как

2023-07-16 20:36 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +@RequiredArgsConstructor(onConstructor_ = @Autowired)
Идея с разделением тестов по разным классам мне нравилась больше, а то получится у вас довольно громоздкий класс

2023-07-18 07:24 UTC, Brill1983 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        return new ErrorResponse(errors.toString()); // для вывода трейса или
Исправил

2023-07-18 07:25 UTC, Brill1983 commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +    Genre findGenreById(@PathVariable int id) {
Исправил

2023-07-18 07:25 UTC, Brill1983 commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +@Slf4j
Исправил

2023-07-18 07:25 UTC, Brill1983 commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaCategoryController.java
> +    MpaCategory findMpaCategoryById(@PathVariable int id) {
Исправил

2023-07-18 07:25 UTC, Brill1983 commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaCategoryController.java
> +@Slf4j
Исправил

2023-07-18 07:28 UTC, Brill1983 commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    public boolean equals(Object o) {
Мне нужна была возможность проводить сравнение не по всем полям, а только по ID, поэтому не хотел использовать стандартные equals и hashCode от Lambock. Теперь переделал так, код equals и hashCode методов уже не нужен.

2023-07-18 07:29 UTC, Brill1983 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Film film2 = filmStorage.addFilm(film);
Исправил.

2023-07-18 07:34 UTC, Brill1983 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        filmValidator.valid(film);
Хотел бы оставить как есть, потому что мне так кажется логичнее:
- нам очень часто в методы передают только id фильма, не объект целиком и id надо проверять на наличие в базе гораздо чаще чем сам объект film;
- если добавить такую же проверку на наличие в базе id внутрь метода, проверяющего входящий объект film, то придется задублировать код с первым методом и эта валидацию будет применима только в одном месте - в updateFilm.

2023-07-18 07:35 UTC, Brill1983 commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +    public Genre findGenreById(int id) { // TODO check how works validation
Исправил. Видимо забыл удалить после проверки работоспособности, извините.

2023-07-18 07:35 UTC, Brill1983 commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +@Slf4j
Исправил

2023-07-18 07:36 UTC, Brill1983 commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaCategoryService.java
> +@Slf4j
исправил

2023-07-18 07:38 UTC, Brill1983 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        System.out.println(rate);
Исправил. Остался фантом от отладки видимо.

2023-07-18 07:38 UTC, Brill1983 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        int rate = rs.getInt("RT");
Исправил

2023-07-18 07:42 UTC, Brill1983 commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +@RequiredArgsConstructor(onConstructor_ = @Autowired)
Разделил на 4 класса.

2023-07-18 17:45 UTC, Frilock approved these changes
Принято, успехов на групповом проекте

2023-07-19 13:36 UTC, merged